### PR TITLE
feat: add `ToHexExt` trait to support prefix

### PR DESCRIPTION
**Pull request by yjhmelody**
Since this crate have supported to decode prefix `0x`.

### CODE REVIEW

**Comment by yjhmelody** [comment]
Hi @DaniPopes  any problem?

**Comment by DaniPopes** [comment]
Thanks for the contribution!

I deprecated the `ToHex` trait because I couldn't see a use case for the `FromIterator` return value and it is much slower than just using the free functions.

I can see this Ext trait being useful as a replacement and improvement of the original, I'd prefer if you re-implemented the other two non-prefix methods and returned `String`s instead by just using the global free functions.
You would also have to move the item export (and the `mod`) to outside of the `cfg_if` so that it's not `cfg`'d out with the `"hex"` feature.

**Comment by yjhmelody** [comment]
Sorry, I don't seem to understand your ideas accurately. Could you merge it and improve it according to your ideas?(Includes possible APIs name improvements.)

**Review by DaniPopes — APPROVED** [review]

**Comment by DaniPopes** [comment]
Released in [`1.11.0`](https://crates.io/crates/const-hex/1.11.0).

**Pull request merged**
